table 'dwh dim_driver'
	lineageTag: 573fa1ae-1a5c-4d2f-957c-fc4bbb7cb52b

	column driver_sk
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: fe304598-dd44-474c-a427-67564ed6827b
		summarizeBy: none
		sourceColumn: driver_sk

		annotation SummarizationSetBy = Automatic

	column driver_id
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 5d0b0249-77cc-43c4-8851-6be8c9742a08
		summarizeBy: none
		sourceColumn: driver_id

		annotation SummarizationSetBy = Automatic

	column shift
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 6bb0ee65-0311-461f-8706-815a9046b67a
		summarizeBy: none
		sourceColumn: shift

		annotation SummarizationSetBy = Automatic

	column vehicle_type
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 85f47a52-3df2-47f4-8fa3-4e134c217246
		summarizeBy: none
		sourceColumn: vehicle_type

		annotation SummarizationSetBy = Automatic

	column hire_date
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 3e3c06de-df78-4b57-aa52-16b08fa4d1d9
		summarizeBy: none
		sourceColumn: hire_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column rating_avg
		dataType: double
		sourceProviderType: decimal
		lineageTag: bf943429-aac5-4f5c-84b7-dec859fe2148
		summarizeBy: sum
		sourceColumn: rating_avg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column on_time_rate
		dataType: double
		sourceProviderType: decimal
		lineageTag: cd782ead-5a0a-42c6-b829-f62ae1f1d734
		summarizeBy: sum
		sourceColumn: on_time_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cancel_rate
		dataType: double
		sourceProviderType: decimal
		lineageTag: bfa90d5b-6a6d-421d-87f2-1b639b6f88b5
		summarizeBy: sum
		sourceColumn: cancel_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: af8769d0-1f7f-4871-b75b-2d59451028f7
		summarizeBy: none
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		isNullable: false
		formatString: Long Date
		sourceProviderType: date
		lineageTag: 53035b41-f090-4f02-a88b-5601ac866b65
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column end_date
		dataType: dateTime
		formatString: Long Date
		sourceProviderType: date
		lineageTag: cba0bb59-f517-42b4-8f96-349903d500f9
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column is_current
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		lineageTag: ceedd96d-204f-42f7-b450-ba21a3dcc428
		summarizeBy: none
		sourceColumn: is_current

		annotation SummarizationSetBy = Automatic

	partition 'dwh dim_driver' = m
		mode: directQuery
		source =
				let
				    Source = PostgreSQL.Database("localhost:5432", "dwh_db"),
				    dwh_dim_driver = Source{[Schema="dwh",Item="dim_driver"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dwh_dim_driver,{{"driver_id", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

