table Measures_Table
	lineageTag: 75c6507e-d049-4f13-8dd9-873cb2349bba

	measure 'Total Tickets' = DISTINCTCOUNT('dwh fact_tickets'[ticket_id])
		formatString: 0
		lineageTag: 0772d7c0-f209-4fd8-9dc2-6750749f9ba0

	measure 'SLA Breach Rate %' =
			
			DIVIDE(
			    COUNTROWS(
			        FILTER(
			            'dwh fact_tickets',
			            'dwh fact_tickets'[resolved_on_time] = FALSE()
			        )
			    ),
			    [Total Tickets],
			    0
			) * 100
		lineageTag: 9a6a9ebd-edec-4a04-aace-8309ec06b1a7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Resolution Time (min)' =
			
			AVERAGEX(
			    FILTER(
			        'dwh fact_tickets',
			        NOT( ISBLANK( 'dwh fact_tickets'[resolve_from_creating_min] ) )
			    ),
			    'dwh fact_tickets'[resolve_from_creating_min]
			)
		lineageTag: f3109cfd-244d-4f4c-962d-f795a7c3f728

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg First Response Time (min)' =
			
			AVERAGEX(
			    FILTER(
			        'dwh fact_tickets',
			        NOT( ISBLANK( 'dwh fact_tickets'[resolve_from_response_min] ) )
			    ),
			    'dwh fact_tickets'[resolve_from_response_min]
			)
		lineageTag: 8128cbff-36d0-422a-8b5c-760e9dfca08a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Refund Amount' =
			
			SUM( 'dwh fact_tickets'[refund_amount] )
		formatString: 0.000
		lineageTag: d798926c-0644-41df-9bed-68564acb4be4

	partition Measures_Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

